server:
  port: 8080
  servlet:
    context-path: /dpm

spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dpm?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    filters: stat,wall,log4j
    maxActive: 20
    inisitalSize: 1
    maxWait: 60000
    poolPreparedStatements: false
    
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    generate-ddl: true
logging:
  file: target/app.log
  level:
    root: INFO
    com.ibm.dpm: debug
    